"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BooleanIResultOutput = void 0;
/**
* 泛型结果输出接口
*/
var BooleanIResultOutput = exports.BooleanIResultOutput = /** @class */ (function () {
    function BooleanIResultOutput() {
    }
    BooleanIResultOutput.getAttributeTypeMap = function () {
        return BooleanIResultOutput.attributeTypeMap;
    };
    BooleanIResultOutput.discriminator = undefined;
    BooleanIResultOutput.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        }
    ];
    return BooleanIResultOutput;
}());
