"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BooleanDataRes = void 0;
var BooleanDataRes = exports.BooleanDataRes = /** @class */ (function () {
    function BooleanDataRes() {
    }
    BooleanDataRes.getAttributeTypeMap = function () {
        return BooleanDataRes.attributeTypeMap;
    };
    BooleanDataRes.discriminator = undefined;
    BooleanDataRes.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ResCode",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "boolean",
            "format": ""
        }
    ];
    return BooleanDataRes;
}());
