"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaptchaData = void 0;
var CaptchaData = exports.CaptchaData = /** @class */ (function () {
    function CaptchaData() {
    }
    CaptchaData.getAttributeTypeMap = function () {
        return CaptchaData.attributeTypeMap;
    };
    CaptchaData.discriminator = undefined;
    CaptchaData.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "backgroundImage",
            "baseName": "backgroundImage",
            "type": "string",
            "format": ""
        },
        {
            "name": "sliderImage",
            "baseName": "sliderImage",
            "type": "string",
            "format": ""
        }
    ];
    return CaptchaData;
}());
