"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LoginViewModel = void 0;
var LoginViewModel = exports.LoginViewModel = /** @class */ (function () {
    function LoginViewModel() {
    }
    LoginViewModel.getAttributeTypeMap = function () {
        return LoginViewModel.attributeTypeMap;
    };
    LoginViewModel.discriminator = undefined;
    LoginViewModel.attributeTypeMap = [
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "passwordKey",
            "baseName": "passwordKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "captchaId",
            "baseName": "captchaId",
            "type": "string",
            "format": ""
        },
        {
            "name": "captchaData",
            "baseName": "captchaData",
            "type": "string",
            "format": ""
        }
    ];
    return LoginViewModel;
}());
