"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Menu = void 0;
var Menu = exports.Menu = /** @class */ (function () {
    function Menu() {
    }
    Menu.getAttributeTypeMap = function () {
        return Menu.attributeTypeMap;
    };
    Menu.discriminator = undefined;
    Menu.attributeTypeMap = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "Meta",
            "format": ""
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<Menu>",
            "format": ""
        },
        {
            "name": "component",
            "baseName": "component",
            "type": "string",
            "format": ""
        }
    ];
    return Menu;
}());
