"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Meta = void 0;
var Meta = exports.Meta = /** @class */ (function () {
    function Meta() {
    }
    Meta.getAttributeTypeMap = function () {
        return Meta.attributeTypeMap;
    };
    Meta.discriminator = undefined;
    Meta.attributeTypeMap = [
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "notCache",
            "baseName": "notCache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "access",
            "baseName": "access",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "isNewWindow",
            "baseName": "isNewWindow",
            "type": "boolean",
            "format": ""
        }
    ];
    return Meta;
}());
