"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageDataReq = void 0;
var PageDataReq = exports.PageDataReq = /** @class */ (function () {
    function PageDataReq() {
    }
    PageDataReq.getAttributeTypeMap = function () {
        return PageDataReq.attributeTypeMap;
    };
    PageDataReq.discriminator = undefined;
    PageDataReq.attributeTypeMap = [
        {
            "name": "pageNum",
            "baseName": "pageNum",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "string",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "{ [key: string]: any; }",
            "format": ""
        }
    ];
    return PageDataReq;
}());
