"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PubDepartment = void 0;
var PubDepartment = exports.PubDepartment = /** @class */ (function () {
    function PubDepartment() {
    }
    PubDepartment.getAttributeTypeMap = function () {
        return PubDepartment.attributeTypeMap;
    };
    PubDepartment.discriminator = undefined;
    PubDepartment.attributeTypeMap = [
        {
            "name": "deptCode",
            "baseName": "deptCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "deptName",
            "baseName": "deptName",
            "type": "string",
            "format": ""
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentCode",
            "baseName": "parentCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "deptLevel",
            "baseName": "deptLevel",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "lmid",
            "baseName": "lmid",
            "type": "string",
            "format": ""
        },
        {
            "name": "lmdt",
            "baseName": "lmdt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "stopFlag",
            "baseName": "stopFlag",
            "type": "boolean",
            "format": ""
        }
    ];
    return PubDepartment;
}());
