"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PubFunctionListDataRes = void 0;
var PubFunctionListDataRes = exports.PubFunctionListDataRes = /** @class */ (function () {
    function PubFunctionListDataRes() {
    }
    PubFunctionListDataRes.getAttributeTypeMap = function () {
        return PubFunctionListDataRes.attributeTypeMap;
    };
    PubFunctionListDataRes.discriminator = undefined;
    PubFunctionListDataRes.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ResCode",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<PubFunction>",
            "format": ""
        }
    ];
    return PubFunctionListDataRes;
}());
