"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PubRoleListDataRes = void 0;
var PubRoleListDataRes = exports.PubRoleListDataRes = /** @class */ (function () {
    function PubRoleListDataRes() {
    }
    PubRoleListDataRes.getAttributeTypeMap = function () {
        return PubRoleListDataRes.attributeTypeMap;
    };
    PubRoleListDataRes.discriminator = undefined;
    PubRoleListDataRes.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ResCode",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<PubRole>",
            "format": ""
        }
    ];
    return PubRoleListDataRes;
}());
