/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Track } from '../models/Track';
import { HttpFile } from '../http/http';

export class SlideTrack {
    'backgroundImageWidth'?: number;
    'backgroundImageHeight'?: number;
    'sliderImageWidth'?: number;
    'sliderImageHeight'?: number;
    'startTime'?: Date;
    'endTime'?: Date;
    'tracks'?: Array<Track> | null;
    'percent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "backgroundImageWidth",
            "baseName": "backgroundImageWidth",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "backgroundImageHeight",
            "baseName": "backgroundImageHeight",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sliderImageWidth",
            "baseName": "sliderImageWidth",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "sliderImageHeight",
            "baseName": "sliderImageHeight",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "tracks",
            "baseName": "tracks",
            "type": "Array<Track>",
            "format": ""
        },
        {
            "name": "percent",
            "baseName": "percent",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return SlideTrack.attributeTypeMap;
    }

    public constructor() {
    }
}

