"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Track = void 0;
var Track = exports.Track = /** @class */ (function () {
    function Track() {
    }
    Track.getAttributeTypeMap = function () {
        return Track.attributeTypeMap;
    };
    Track.discriminator = undefined;
    Track.attributeTypeMap = [
        {
            "name": "x",
            "baseName": "x",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "t",
            "baseName": "t",
            "type": "number",
            "format": "int32"
        }
    ];
    return Track;
}());
