"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidateResult = void 0;
var ValidateResult = exports.ValidateResult = /** @class */ (function () {
    function ValidateResult() {
    }
    ValidateResult.getAttributeTypeMap = function () {
        return ValidateResult.attributeTypeMap;
    };
    ValidateResult.discriminator = undefined;
    ValidateResult.attributeTypeMap = [
        {
            "name": "result",
            "baseName": "result",
            "type": "ValidateResultType",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }
    ];
    return ValidateResult;
}());
