"use strict";
/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.VPubuserDeptPageDateRes = void 0;
var VPubuserDeptPageDateRes = exports.VPubuserDeptPageDateRes = /** @class */ (function () {
    function VPubuserDeptPageDateRes() {
    }
    VPubuserDeptPageDateRes.getAttributeTypeMap = function () {
        return VPubuserDeptPageDateRes.attributeTypeMap;
    };
    VPubuserDeptPageDateRes.discriminator = undefined;
    VPubuserDeptPageDateRes.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ResCode",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "totalPage",
            "baseName": "totalPage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<VPubuserDept>",
            "format": ""
        },
        {
            "name": "pageNum",
            "baseName": "pageNum",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number",
            "format": "int32"
        }
    ];
    return VPubuserDeptPageDateRes;
}());
