/**
 * CNet API
 * CNet基础框架API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WeatherForecast {
    'date'?: Date;
    'temperatureC'?: number;
    'temperatureF'?: number;
    'summary'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "temperatureC",
            "baseName": "temperatureC",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "temperatureF",
            "baseName": "temperatureF",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WeatherForecast.attributeTypeMap;
    }

    public constructor() {
    }
}

